### PR TITLE
fix continuing lookupSync bug

### PR DESCRIPTION
**Pull request by dankang**
bug fix for continuing lookupSync:
##### before
````
console.log(countryObj.lookupSync('8.8.8.8').country_code); // It should be 'US'. The output is 'US'.
console.log(countryObj.lookupSync('168.126.63.1').country_code); // It should be 'KR'. But, the output is 'US'.
````

I fixed nan codes and added test cases above.
##### after
````
console.log(countryObj.lookupSync('8.8.8.8').country_code);   // It should be 'US'. The output is 'US'.
console.log(countryObj.lookupSync('168.126.63.1').country_code); // It should be 'KR'. The output is 'KR'.
````

Also, I fixed segmentation fault in my previous pull request.

Thanks!

### CODE REVIEW

**Comment by kuno** [comment]
Cool, thanks ! :+1: 

Are all the submodules has been fixed ?

**Comment by dankang** [comment]
Yes, I think that I did all.

**Comment by kuno** [comment]
I saw the commit for segmentation fault only contains code for `city` and `city6` module.

Are you sure other sub-module dose not need to fix ?

**Comment by dankang** [comment]
Yes, I'm sure.

Only city and city6 have the segmentation fault problem in codes.

**Comment by kuno** [comment]
ok, thank you very much !

**Pull request merged**
